---

- name: Retrieve tenantID
  shell: keystone --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }}
         tenant-list | awk '/ {{ item }} / { print $2 }'
  with_items: tenantname
  register: tenantid

- debug: var=tenantid

- name: Test
  debug: msg="Test id {{ item.stdout }}"
  with_items: tenantid.results

#- name: Adjust tenant quotas
#  command: nova --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }} 
#           quota-update {{ item.0 }} {{ item.1 }}
#  with_together:
#    - qoptions
#    - tenantid.stdout
