---
# This playbook used to configure Multi-Tenant Isolation. 

- hosts: galera_container
  user: root
  remote_user: root
  sudo: yes
  roles:
    - cloud-inventory
    
- hosts: utility_container
  user: root
  remote_user: root
  sudo: yes
  roles:
    - cloud-usage