---

- name: Launch instances in tenant
  command: nova --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }} 
           boot --flavor {{ FLAVOR }} --image {{ OSIMG }} --nic net-id={{ SHARED_NETWORK }} --security-group default --key-name {{ KEY_NAME }} 
           --min-count {{ INSTCNT }} {{ INSTNAME }}