---

- name: Retrieve tenantID
  shell: keystone --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }}
         tenant-list | awk '/ {{ tenantname }} / { print $2 }'
  register: tenantid

- name: Retrieve instance name from tenant
  shell: nova --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }}
           list --all-tenants --tenant {{ tenantid.stdout }} --minimal | awk 'NR > 2 { print $4 }'
  register: instname

- debug: var=instname

- debug: msg="{{ item.stdout.split('\n') }}"
  with_items: instname

#- name: Create instance snapshot
#  command: nova --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }} 
#           image-create {{ item }} snap-{{ item }}
#  with_items: instname.results
#  when: item.stdout.split('\n')
