---

- name: Retrieve instance name from tenant
  command: nova list --all-tenants 0 --tenant {{ item }} --fields Name
  with_items: tenantname
  register: instname

- name: Delete instanaces by tenant
  command: nova --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }} 
           delete {{ item }}
  with_items: instname.stdout_lines

- name: Destroy user environments
  command: keystone --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }} 
           tenant-delete {{ item }}
  with_items: tenantname

- name: Delete users
  command: keystone --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }} 
           user-delete {{ item }}
  with_items: userid